package com.tookancustomer.filter.constants;

public interface FilterConstants {
    String EXTRA_ACTION = "EXTRA_ACTION";
    String ACTION_APPLY="ACTION_APPLY";
    String ACTION_CLEAR_ALL="ACTION_CLEAR_ALL";
    String EXTRA_BUSINESS_CATEGORY_ID="EXTRA_BUSINESS_CATEGORY_ID";
    String EXTRA_BUSINESS_CATEGORY_ALL="EXTRA_BUSINESS_CATEGORY_ALL";
    String EXTRA_BUSINESS_CATEGORY="EXTRA_BUSINESS_CATEGORY";

    int REQUEST_CODE_TO_OPEN_FILTER=1001;

}
