package com.tookancustomer.appdata;

public interface TerminologyStrings {
    String TERMINOLOGY = "TERMINOLOGY_TERMINOLOGY";
    String QRCODE_QRCODE = "QRCODE_QRCODE";

    String APP_NAME = "APP_NAME";

    String NAME = "NAME_NAME";
    String QUANTITY = "123";
    String AMOUNT = "123";
    String UNIT_TYPE = "UNITTYPE_UNITTYPE";
    String DATE = "DATE_DATE";


    String ORDER = "ORDER_ORDER";
    String ADDRESS = "ADDRESS_ADDRESS";
    String LANDMARK = "LANDMARK_LANDMARK";
    String APARTMENT = "APARTMENT_APARTMENT";


    String POSTALCODE = "POSTALCODE_POSTALCODE";
    String ORDERS = "ORDERS_ORDERS";
    String AGENT = "AGENT_AGENT";
    String READY_TO_PLACE_YOUR_ORDER = "READY_TO_PLACE_YOUR_ORDER";

    String ITEM = "ITEM_ITEM";
    String ITEMS = "ITEMS_ITEMS";
    String SELFPICKUP_SELFPICKUP = "SELFPICKUP_SELFPICKUP";

    String MERCHANT = "MERCHANT_MERCHANT";
    String MERCHANTS = "MERCHANTS_MERCHANTS";

    String STORE = "STORE_STORE";
    String STORES = "STORES_STORES";

    String PICKUP = "PICKUP_PICKUP";
    String DELIVERY = "DELIVERY_DELIVERY";

    String START_TIME = "STARTTIME_STARTTIME";
    String END_TIME = "ENDTIME_ENDTIME";

    String GIFT_CARD = "GIFTCARD_GIFTCARD";
    String BUY = "BUY_BUY";
    String REDEEM = "REDEEM_REDEEM";
    String WALLET = "WALLET_WALLET";
    String LOYALTY_POINTS = "LOYALTYPOINTS_LOYALTYPOINTS";
    String PAYMENT = "PAYMENT_PAYMENT";

    String NOTIFICATION = "NOTIFICATIONS_NOTIFICATIONS";
    String CUSTOMER = "CUSTOMER_CUSTOMER";

    String PRODUCT = "PRODUCT_PRODUCT";
    String REWARDS = "REWARDS_REWARDS";
    String PRODUCTS = "PRODUCTS_PRODUCTS";
    String CART = "CART_CART";
    String CHECKOUT = "CHECKOUT_CHECKOUT";
    String TIP = "TIP_TIP";

    String CUSTOM_ORDER = "CUSTOMORDER_CUSTOMORDER";
    String START__TEXT = "STARTTEXT_STARTTEXT";
    String START__TEXT_SMALL = "starttext_starttext";
    String COUNT_COUNT = "COUNT_COUNT";
    String CURRENCY_CURRENCY = "CURRENCY_CURRENCY";

    String SURGE = "SURGE_SURGE";
    String SURGE_MSG = "SURGE_MSG";

    String HOME_DELIVERY = "HOME_DELIVERY";
    String TAKE_AWAY = "TAKE_AWAY";
    String PROJECTS = "PROJECTS_PROJECTS";
    String PICKUP_AND_DROP = "PICKUP_AND_DROP";
    String YOUR_ORDER_DESCRIPTION = "YOUR_ORDER_DESCRIPTION_YOUR_ORDER_DESCRIPTION";
}